### ISSUE TITLE
Update Newsletter theme CSS

### ISSUE THREAD

**Issue by ericgregorich** [ericgregorich/micro-blog-cards-theme#1]
Add some simple formatting to give the newsletter a facelift to match this theme.

**Comment by rmdes** [comment]
How do you enable the newsletter features of this theme ?

**Comment by ericgregorich** [comment]
> How do you enable the newsletter features of this theme? 
> 
> 

Do you have Micro.blog premium? The newsletter feature is part of the service itself, not the theme. 

I looked at some CSS that will update the newsletter to match the theme, but it isn't straightforward. We can only do a few cosmetic tweaks. 

I have some extra CSS in my Design page in my Micro.blog account that does this. I'll try to share the CSS soon.

**Comment by rmdes** [comment]
Yes I do have Premium blog.rmendes.net I'll try to figure out where this is hidden, thanks for your answer and for this nice theme!

**Comment by ericgregorich** [comment]
Thanks. You should have Newsletter in the left menu of your micro.blog account. Here is a screenshot of mine on mobile. On desktop it would be in the left menu. 

![image](https://user-images.githubusercontent.com/26981280/235011730-98183ba6-6c31-48c1-a675-343503d8c368.png)

If not, check Account > View Subscriptions. You may need to reach out to Micro.blog help if you still don't see it.
