### ISSUE TITLE
Post category buttons style

### ISSUE THREAD

**Issue by jfmartin67** [ericgregorich/micro-blog-cards-theme#10]
Could the category buttons corners be similar to the card's corners (radius)?
![Safari-Personal (Default) — This is a title - Numeric Citizen Blog (Test)@2024-01-28@07 47 55@2x](https://github.com/ericgregorich/micro-blog-cards-theme/assets/211377/12453425-37cb-4b4f-9025-24dfcec28005)

**Comment by ericgregorich** [comment]
I'm going to make some tweaks to the default tags and the buttons at the bottom of the posts. Maybe some other tweaks. 

I'll probably work on it today.

**Comment by ericgregorich** [comment]
This should be updated in v1.6, which I pushed out.
