### ISSUE TITLE
Is "Reply with Mastodon" supported?

### ISSUE THREAD

**Issue by jfmartin67** [ericgregorich/micro-blog-cards-theme#12]
Title says it all.

**Comment by ericgregorich** [comment]
Not yet, but it will soon!

**Comment by ericgregorich** [comment]
Version 1.6 should be available, and if you install the Reply on Mastodon plugin, it should appear on your posts.

**Comment by tartanhare** [comment]
I see you closed this, but installing the Reply on Mastodon plugin does not make the button appear on my posts (running 1.8).

PS: Thanks for the theme, loving it.

**Comment by ericgregorich** [comment]
@tartanhare The Reply with Mastodon button will not appear on every post. I believe that it only appears on posts that have been cross posted from the Micro.blog feeds. 

I'm not 100% certain how it works to be honest. I know my older posts don't have it and my new posts that I cross posted do. 

If that's not the case for you, let me know and I'll see if there something else going on. 

Please provide a link to a post where you expect it to appear.

**Comment by tartanhare** [comment]
Ah, I see... I have clearly misunderstood the RoM plugin. I thought it was for readers users to reply to my posts via _their_ Mastodon, rather than reply to _my_ Mastodon account.

**Comment by ericgregorich** [comment]
> Ah, I see... I have clearly misunderstood the RoM plugin. I thought it was for readers users to reply to my posts via _their_ Mastodon, rather than reply to _my_ Mastodon account.

Yep, that got me when I first installed it also.
