### ISSUE TITLE
Are the footnotes numbering working?

### ISSUE THREAD

**Issue by jfmartin67** [ericgregorich/micro-blog-cards-theme#13]
I do have this blog post on my testing website ([link](https://numericcitizen-test.micro.blog/2023/09/11/this-is-a.html)), and the footnote numbers aren't increasing.

**Comment by ericgregorich** [comment]
I'm not having any problems.

Here is a [link to my test post](https://ericgregorich-test.micro.blog/2024/01/28/test-footnote-test.html#fnref:1). 

And the markdown I used looks like this.

```
Test Footnote 1 [^Test1]
Test Footnote 2 [^Test2]
Test Footnote 3 [^Test3]

[^Test1]: This is footnote 1.
[^Test2]: This is footnote 2.
[^Test3]: This is footnote 3
```

Do you have a plugin installed? I tried the Bigfoot plugin and it seemed to work fine, but it hides the number with ... Your test has a number, so I don't know how that's being generated.

**Comment by jfmartin67** [comment]
Wel, if I don't use the numbers, the ... shows correctly.
