### ISSUE TITLE
Hugo 0.117 seems ok, update installation instructions?

### ISSUE THREAD

**Issue by jfmartin67** [ericgregorich/micro-blog-cards-theme#14]
Title says it all.

**Comment by ericgregorich** [comment]
Go to your Plugins screen in your Micro.blog account. When the plugin is ready it should have an Upgrade button and a message saying a new version is available. Click Upgrade.

![CleanShot 2024-01-28 at 14 45 29](https://github.com/ericgregorich/micro-blog-cards-theme/assets/26981280/4c7bf05e-2453-4de1-bfb8-8d59aca4b8a9)

**Comment by ericgregorich** [comment]
And yes, the Cards Theme has supported Hugo 0.117 shortly after it became available on Micro.blog.
