### ISSUE TITLE
Text color in footnote popover?

### ISSUE THREAD

**Issue by jfmartin67** [ericgregorich/micro-blog-cards-theme#15]
Is this color exposed in the plugin settings ? Can't find which is which for this specific color spec. 
![Safari-Personal (Default) — Numeric Citizen Blog (Test)@2024-01-28@18 31 02@2x](https://github.com/ericgregorich/micro-blog-cards-theme/assets/211377/f272dbfd-8c60-4468-aed5-dd1915789da8)

**Comment by jfmartin67** [comment]
Still to pale text in 1.8.

**Comment by ericgregorich** [comment]
I just now updated this to test. If you go to Design > Edit Custom Themes > Cards Theme, and click on the Refresh icon, it should pull the latest update from GitHub with this change. 

![CleanShot 2024-02-04 at 16 42 59](https://github.com/ericgregorich/micro-blog-cards-theme/assets/26981280/7cfb8c76-d84c-43bb-a38e-de0443818884)

**Comment by jfmartin67** [comment]
Mmmm... did you push 1.8.1 or ? I don't see anything like a Refresh button... when editing the Custom theme... Sorry, I must be tired...

**Comment by ericgregorich** [comment]
> Mmmm... did you push 1.8.1 or ? I don't see anything like a Refresh button... when editing the Custom theme... Sorry, I must be tired... 

It's not a new version yet. But you should be able to pull it down manually to test it. 

Design > Edit Custom Themes > Cards Theme, and click on the Refresh icon (among the buttons across the top between the Duplicate and New Theme button).

**Comment by jfmartin67** [comment]
1.8.1 fixes this issue. Thanks.
