### ISSUE TITLE
Conversation indicator on home page?

### ISSUE THREAD

**Issue by jfmartin67** [ericgregorich/micro-blog-cards-theme#18]
Do you think it is possible to display a conversation indicator at the bottom of a post (on the home page) if there are replies to a post?

**Comment by ericgregorich** [comment]
I'd be concerned about performance. The conversations.js would need to be called for every post listed to see if there are replies. It doesn't seem like a wise thing to add. 

But I can look into it in case there is another way.

**Comment by jfmartin67** [comment]
Could point. Thanks.
