### ISSUE TITLE
Centered images in blog post?

### ISSUE THREAD

**Issue by jfmartin67** [ericgregorich/micro-blog-cards-theme#19]
I think that images in blog posts should be centered. What do you think?

**Comment by ericgregorich** [comment]
I agree. I'll add it to the theme sometime this weekend.

In the meantime, you can add this CSS to your Design > Edit CSS in your account settings to apply it now.

```
article img {
display: block;
    margin: auto;
    margin-top: 15px;
}
```

**Comment by jfmartin67** [comment]
Thanks!

**Comment by ericgregorich** [comment]
This is built into v1.7.
