### ISSUE TITLE
Switching viewing modes not screen reader friendly.

### ISSUE THREAD

**Issue by rkingett** [ericgregorich/micro-blog-cards-theme#3]
Hi there! I was testing out the Cards theme, and I really like it so far, but the options, when viewing a blog, to change from dark to light mode don't appear to work with the keyboard or screen reader.

From what I can tell, there are 2 symbols. An upward sun and a downcast moon face or something.

It would be better to make this a toggle, or even better yet, buttons with states like on, and off, or selected, and not.

Apart from that, this theme appears to be screen reader friendly!

**Comment by ericgregorich** [comment]
The Theme switcher control has been removed entirely in favor of automatically switching based on your OS.
