### ISSUE TITLE
Adding video breaks the mobile site. 

### ISSUE THREAD

**Issue by Jezebelley** [ericgregorich/micro-blog-cards-theme#8]
Currently when adding an mp4 file the embed breaks the mobile formatting. Is there a way to modify the theme to correct this? Thank you!

![Screenshot_20240123-162129](https://github.com/ericgregorich/micro-blog-cards-theme/assets/157225443/6acc919f-7db5-4d19-9169-eff419848e78)

**Comment by ericgregorich** [comment]
I'll take a look when I can, probably this weekend. Thanks!

**Comment by ericgregorich** [comment]
I did recreate an issue with YouTube embeds, and fixed it. The fix should be published later today.
I may need a link your post so I can verify the fix is working for your embed. I don't know if it will be the same fix as the YouTube embed.

**Comment by ericgregorich** [comment]
I pushed out v1.6. Let me know if this doesn't fix your issue, and if not, send me a link to your page so I can troubleshoot. Thanks!

**Comment by jfmartin67** [comment]
For me it works great on mobile (iPhone)

**Comment by Jezebelley** [comment]
Looking good! Thanks for the fix!
