### ISSUE TITLE
Incomplete button at bottom of each post

### ISSUE THREAD

**Issue by jfmartin67** [ericgregorich/micro-blog-cards-theme#9]
I'm testing the Cards theme on my test micro.blog website. The buttons are not well displayed at the bottom of each post
![Safari-Personal (Default) — This is a title - Numeric Citizen Blog (Test)@2024-01-28@07 45 52@2x](https://github.com/ericgregorich/micro-blog-cards-theme/assets/211377/3cdf06de-bc3a-4693-84ec-2e4fcf8e09f6)
.

**Comment by ericgregorich** [comment]
Do you have the "Enable Tinylytics Kudos" setting enabled by chance? If its enabled but Tinylytics isn't configured, it would show an empty button.

**Comment by jfmartin67** [comment]
Yes. I'll disable it. And the reply by email thing is also corrected as the plunging settings weren't set. Sorry for that one.
